### ISSUE TITLE
fix 'invalid port: None' error?

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/funnel_cake_index#10]
`/tmp/airflowtmph57hny4e/tmp/funnel_cake_index/lib/funnel_cake_index/indexer_config.rb:40 Addressable::URI::InvalidURIError:Invalid port number: "None"`

Would be nice for this library to be able to handle a port of "None"

**Comment by nomadicoder** [comment]
@cmharlow I'll dig into the ruby `HTTPClient` class docs to see if we have to explicitly give a port number. You'd think it would default to 80. What URI is `solr_uri` we are sending to set_auth?
